// <auto-generated />
namespace ZelectroCom.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update180915 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update180915));
        
        string IMigrationMetadata.Id
        {
            get { return "201509180825190_Update180915"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
