// <auto-generated />
namespace ZelectroCom.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update021015 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update021015));
        
        string IMigrationMetadata.Id
        {
            get { return "201510012121152_Update021015"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
