//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZelectroCom.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZelectroCom.Web.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переместить в группы.
        /// </summary>
        public static string BF_GroupEditorMoveToGroups {
            get {
                return ResourceManager.GetString("BF_GroupEditorMoveToGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string BF_Items {
            get {
                return ResourceManager.GetString("BF_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        public static string BF_New {
            get {
                return ResourceManager.GetString("BF_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет записей.
        /// </summary>
        public static string BF_NoResults {
            get {
                return ResourceManager.GetString("BF_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to из.
        /// </summary>
        public static string BF_Of {
            get {
                return ResourceManager.GetString("BF_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить.
        /// </summary>
        public static string BF_Reset {
            get {
                return ResourceManager.GetString("BF_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to записей на странице.
        /// </summary>
        public static string BF_ResultsPerPage {
            get {
                return ResourceManager.GetString("BF_ResultsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string BF_Save {
            get {
                return ResourceManager.GetString("BF_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string BF_Search {
            get {
                return ResourceManager.GetString("BF_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string BF_Select {
            get {
                return ResourceManager.GetString("BF_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Черновики.
        /// </summary>
        public static string DraftListVm_Drafts {
            get {
                return ResourceManager.GetString("DraftListVm_Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        public static string DraftRowVm_ArticleState {
            get {
                return ResourceManager.GetString("DraftRowVm_ArticleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string DraftRowVm_CreatedDate {
            get {
                return ResourceManager.GetString("DraftRowVm_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздел.
        /// </summary>
        public static string DraftRowVm_Section {
            get {
                return ResourceManager.GetString("DraftRowVm_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string DraftRowVm_Title {
            get {
                return ResourceManager.GetString("DraftRowVm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последнее обновление.
        /// </summary>
        public static string DraftRowVm_UpdatedDate {
            get {
                return ResourceManager.GetString("DraftRowVm_UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время публикации.
        /// </summary>
        public static string DraftVm_PublishTime {
            get {
                return ResourceManager.GetString("DraftVm_PublishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        public static string DraftVm_Rating {
            get {
                return ResourceManager.GetString("DraftVm_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздел.
        /// </summary>
        public static string DraftVm_SectionId {
            get {
                return ResourceManager.GetString("DraftVm_SectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите раздел для статьи.
        /// </summary>
        public static string DraftVm_SectionId_Prompt {
            get {
                return ResourceManager.GetString("DraftVm_SectionId_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO описание.
        /// </summary>
        public static string DraftVm_SeoDescription {
            get {
                return ResourceManager.GetString("DraftVm_SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO ключевые слова.
        /// </summary>
        public static string DraftVm_SeoKeywords {
            get {
                return ResourceManager.GetString("DraftVm_SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO заголовок.
        /// </summary>
        public static string DraftVm_SeoTitle {
            get {
                return ResourceManager.GetString("DraftVm_SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO URL.
        /// </summary>
        public static string DraftVm_SeoUrl {
            get {
                return ResourceManager.GetString("DraftVm_SeoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string DraftVm_Title {
            get {
                return ResourceManager.GetString("DraftVm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название статьи.
        /// </summary>
        public static string DraftVm_Title_Prompt {
            get {
                return ResourceManager.GetString("DraftVm_Title_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во просмотров.
        /// </summary>
        public static string DraftVm_ViewsCount {
            get {
                return ResourceManager.GetString("DraftVm_ViewsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О себе.
        /// </summary>
        public static string EditableUserDataVm_Description {
            get {
                return ResourceManager.GetString("EditableUserDataVm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string EditableUserDataVm_Firstname {
            get {
                return ResourceManager.GetString("EditableUserDataVm_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string EditableUserDataVm_Lastname {
            get {
                return ResourceManager.GetString("EditableUserDataVm_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ник.
        /// </summary>
        public static string EditableUserDataVm_Nickname {
            get {
                return ResourceManager.GetString("EditableUserDataVm_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серверная ошибка.
        /// </summary>
        public static string Error_Server {
            get {
                return ResourceManager.GetString("Error_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редирект старых файлов.
        /// </summary>
        public static string OldMediaListVm_Grid {
            get {
                return ResourceManager.GetString("OldMediaListVm_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый путь.
        /// </summary>
        public static string OldMediaRowVm_NewPath {
            get {
                return ResourceManager.GetString("OldMediaRowVm_NewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый путь.
        /// </summary>
        public static string OldMediaRowVm_OldPath {
            get {
                return ResourceManager.GetString("OldMediaRowVm_OldPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настроить.
        /// </summary>
        public static string ProfileVm_UserInfo {
            get {
                return ResourceManager.GetString("ProfileVm_UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник.
        /// </summary>
        public static string ProfileVm_UserProfile {
            get {
                return ResourceManager.GetString("ProfileVm_UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string PublicationRowVm_Author {
            get {
                return ResourceManager.GetString("PublicationRowVm_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публикации.
        /// </summary>
        public static string PublicationsVm_Grid {
            get {
                return ResourceManager.GetString("PublicationsVm_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки на публикацию.
        /// </summary>
        public static string PubRequestsVm_Grid {
            get {
                return ResourceManager.GetString("PubRequestsVm_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разделы.
        /// </summary>
        public static string SectionListVm_Grid {
            get {
                return ResourceManager.GetString("SectionListVm_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрытый раздел.
        /// </summary>
        public static string SectionVm_IsHidden {
            get {
                return ResourceManager.GetString("SectionVm_IsHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string SectionVm_Name {
            get {
                return ResourceManager.GetString("SectionVm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядок.
        /// </summary>
        public static string SectionVm_Order {
            get {
                return ResourceManager.GetString("SectionVm_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь.
        /// </summary>
        public static string SectionVm_Path {
            get {
                return ResourceManager.GetString("SectionVm_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не может содержать более 50 символов.
        /// </summary>
        public static string Validation_Length50 {
            get {
                return ResourceManager.GetString("Validation_Length50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не может быть пустым.
        /// </summary>
        public static string Validation_RequiredField {
            get {
                return ResourceManager.GetString("Validation_RequiredField", resourceCulture);
            }
        }
    }
}
